# Generated by Django 5.0 on 2024-01-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productgallery",
            name="created",
        ),
        migrations.RemoveField(
            model_name="productgallery",
            name="product",
        ),
        migrations.AddField(
            model_name="product",
            name="gallery",
            field=models.ManyToManyField(
                related_name="gallery_back",
                to="product.productgallery",
                verbose_name="تصاویر محصولات",
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="product", verbose_name="تصویر"
            ),
        ),
    ]
