# Generated by Django 5.0 on 2024-02-03 20:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="field",
            field=models.TextField(
                default="long description", max_length=4000, verbose_name="توضیحات"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="gallery",
            field=models.ManyToManyField(
                help_text="(اندازه تصاویر باید در کمترین حالت ممکن با عرض(width) = 400px بارگذاری شوند تا کیفیت لازمه رو در حداقل ترین حالت ممکنه فراهم کنند. تصاویر حتما باید webp یا png با پس زمینه transparent باشند. بهتر است حجم تصاویر نهایتا 50 الی 100 کیلوبایت باشند.(هرچه کمتر سرعت لود بیشتر))",
                related_name="gallery_back",
                to="product.productgallery",
                verbose_name="تصاویر محصولات",
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="اندازه پیش فرض تصاویر کتگوری ها به صورت width=203px و height=241px است که تجریحا باید به فرمت webp یا درغیر اینصورت jpg و jpeg برای فشرده بودن حجم آن باشد. بهتر است حجم تصاویر نهایتا 50 الی 100 کیلوبایت باشند. برای اندازه تصویر الزامی نیست اما حتما باید ارتفاع(height) بیشتر از عرض(width) آن باشد. یعنی تصویر به صورت عمودی باشد",
                null=True,
                upload_to="product",
                verbose_name="تصویر",
            ),
        ),
    ]
