# Generated by Django 5.0 on 2024-01-22 23:12

import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_image",
                    models.ImageField(upload_to="original_blog/", verbose_name="تصویر"),
                ),
                (
                    "resized_image",
                    imagekit.models.fields.ProcessedImageField(
                        blank=True,
                        null=True,
                        upload_to="resized_blog/",
                        verbose_name="تصویر",
                    ),
                ),
            ],
            options={
                "verbose_name": "گالری وبلاگ",
                "verbose_name_plural": "گالری وبلاگ ها",
            },
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="عنوان")),
                (
                    "description",
                    models.TextField(max_length=2500, verbose_name="توضیحات"),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "gallery",
                    models.ManyToManyField(
                        related_name="back_gallery",
                        to="blog.bloggallery",
                        verbose_name="تصاویر",
                    ),
                ),
            ],
            options={
                "verbose_name": "وبلاگ",
                "verbose_name_plural": "وبلاگ ها",
            },
        ),
    ]
