# Generated by Django 5.0 on 2024-01-13 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="عنوان")),
                (
                    "description",
                    models.TextField(max_length=2500, verbose_name="توضیحات"),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
            ],
            options={
                "verbose_name": "وبلاگ",
                "verbose_name_plural": "وبلاگ ها",
            },
        ),
        migrations.CreateModel(
            name="BlogGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="blog", verbose_name="تصویر")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "blog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="back_blog",
                        to="blog.blog",
                        verbose_name="وبلاگ",
                    ),
                ),
            ],
            options={
                "verbose_name": "گالری وبلاگ",
                "verbose_name_plural": "گالری وبلاگ ها",
            },
        ),
    ]
