# Generated by Django 5.0 on 2024-01-22 14:12

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bloggallery",
            name="resized_image",
            field=imagekit.models.fields.ProcessedImageField(
                blank=True, null=True, upload_to="resized_blog/", verbose_name="تصویر"
            ),
        ),
    ]
