# Generated by Django 5.0 on 2024-01-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fullname",
                    models.CharField(max_length=300, verbose_name="نام و نام خانوادگی"),
                ),
                (
                    "phone",
                    models.CharField(
                        db_index=True, max_length=13, verbose_name="شماره تماس"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=150, null=True, verbose_name="ایمیل"
                    ),
                ),
                ("day", models.PositiveSmallIntegerField(verbose_name="روز هفته")),
                ("hour", models.CharField(max_length=40, verbose_name="ساعت")),
            ],
            options={
                "verbose_name": "تماس با ما",
                "verbose_name_plural": "بخش تماس با ما",
            },
        ),
        migrations.CreateModel(
            name="Hiring",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fullname",
                    models.CharField(max_length=300, verbose_name="نام و نام خانوادگی"),
                ),
                (
                    "phone",
                    models.CharField(
                        db_index=True, max_length=13, verbose_name="شماره تماس"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=150, null=True, verbose_name="ایمیل"
                    ),
                ),
                (
                    "description",
                    models.TextField(max_length=1500, verbose_name="توضیحات"),
                ),
                (
                    "pdf_file",
                    models.FileField(upload_to="hiring", verbose_name="فایل PDF"),
                ),
            ],
            options={
                "verbose_name": "بخش استخدام",
                "verbose_name_plural": "بخش استخدامی ها",
            },
        ),
    ]
