# Generated by Django 5.0 on 2024-01-31 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site_settings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegisterFake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(db_index=True, max_length=150, verbose_name="نام"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=150, verbose_name="نام خانوادگی"),
                ),
                (
                    "phone",
                    models.CharField(
                        db_index=True, max_length=13, verbose_name="شماره تماس"
                    ),
                ),
                (
                    "description",
                    models.TextField(max_length=1000, verbose_name="توضیحات"),
                ),
            ],
            options={
                "verbose_name": "کاربران ثبت نامی",
                "verbose_name_plural": "کاربران ثبت نامی ها",
            },
        ),
    ]
